<h1 align='center'> 파이썬과학프로그래밍기초 실습 7</h1>

<p style="text-align: right"> 2021.4.28.</p>

### <div class="alert alert-block alert-info">
    
- 파일 이름에서 00000000을 자신의 학번으로, name을 자신의 이름으로 수정하세요.

- 다음 줄에 자신의 이름, 학번, 학과(전공)을 적으세요.

* 이름:   이장범        학번: 러시아학과   학과(전공):20171722
    
</div>

- Jupyter notebook에 대한 설명은 [The Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/)을  참고하라

- Markdown은 [Markdown Guide](https://www.markdownguide.org/)를 참고하라.
- [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)

* 과제 제출: 4월 30일 (금) 오후 6:00까지 최종본 제출. 


#### 문제 0: 아래 셀에 다음 명령을 실행하라.

```
import numpy as np
np.__version__
```


In [55]:
import numpy as np
np.__version__

'1.19.2'

#### 문제 1.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)
```

In [118]:
aa=np.arange(8,dtype=np.int16)
aa

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)

#### 문제 2.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int64)
```

In [59]:
np.arange(0,16,2,dtype=np.int64)

array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int64)

#### 문제 3.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([1. , 1.2, 1.4, 1.6, 1.8])
```

In [51]:
np.arange(1.0,2.0,0.2)


array([1. , 1.2, 1.4, 1.6, 1.8])

#### 문제 4.
NumPy의 linspace를 사용하여 다음 ndarray를 만들어라.

```
array([ 0. ,  2.5,  5. ,  7.5, 10. ])
```

In [29]:
np.arange(0.,12.5,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### 문제 5.
NumPy의 linspace를 사용하여 다음 ndarray를 만들어라.

```
array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])
```

In [32]:
np.arange(1.,12.25,2.25)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### 문제 7.
NumPy의 arange와 reshape을 사용하여 다음 ndarray를 만들어라.

```
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]], dtype=int64)
```

In [63]:
np.arange(2,33,2,dtype=np.int64).reshape(4,4)


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]], dtype=int64)

#### 문제 8.
문제 7에서 만든 ndarray에서 4, 12, 20, 28의 합 64를 출력하는 문장 2 개를 작성하라. (서로 다른 두 가지 방법으로 같은 결과를 출력하라)

In [70]:
w=np.arange(2,33,2,dtype=np.int64).reshape(4,4)
w[:,1].sum()

64

In [71]:
w=np.arange(2,33,2,dtype=np.int64).reshape(4,4)
print(w.sum(0)[1])

64


#### 문제 9.
문제 7에서 만든 ndarray에서 18, 20, 22, 24의 합 84를 출력하는 문장 3 개를 작성하라. (서로 다른 두 가지 방법으로 같은 결과를 출력하라)

In [73]:
w=np.arange(2,33,2,dtype=np.int64).reshape(4,4)
w[2,:].sum()

84

In [75]:
w=np.arange(2,33,2,dtype=np.int64).reshape(4,4)
print(w.sum(1)[2])

84


In [116]:
w=np.arange(2,33,2,dtype=np.int64).reshape(4,4)
w[np.arange(3)[2]].sum()

84

#### 문제 10.
문제 7에서 만든 ndarray에서 2, 12, 22, 32의 합 68을 출력하는 문장을 작성하라.

In [81]:
w=np.arange(2,33,2,dtype=np.int64).reshape(4,4)
np.diag(w).sum()


68

#### 문제 11.
문제 7에서 만든 ndarray에서 4, 14, 24의 합 42을 출력하는 문장을 작성하라.

In [82]:
w=np.arange(2,33,2,dtype=np.int64).reshape(4,4)
np.diag(w,1).sum()

42

#### 문제 12.
문제 7에서 만든 ndarray에서 10, 20, 30의 합 60을 출력하는 문장을 작성하라.

In [84]:
np.diag(w,-1).sum()

60

#### 문제 15.
다음 ndarray를 만들고 변수 a에 이 객체를 할당하라. 단, 모든 원소를 직접 나열하면 안된다.

```
array([[[ 3,  6],
        [ 9, 12],
        [15, 18]],

       [[21, 24],
        [27, 30],
        [33, 36]],

       [[39, 42],
        [45, 48],
        [51, 54]],

       [[57, 60],
        [63, 66],
        [69, 72]]])
```

In [86]:
a= np.arange(3,75,3).reshape(4,3,2)
print(a)

[[[ 3  6]
  [ 9 12]
  [15 18]]

 [[21 24]
  [27 30]
  [33 36]]

 [[39 42]
  [45 48]
  [51 54]]

 [[57 60]
  [63 66]
  [69 72]]]


#### 문제 16.
문제 15에서 만든 a에서 9, 27, 45, 63의 합 144를 출력하는 문장을 작성하라.

In [96]:
a= np.arange(3,75,3).reshape(4,3,2)
print(a.sum(1)[2][1])

144


#### 문제 17.
문제 15에서 만든 a와 shape과 dtype이 같고, 모든 원소가 1인 ndarray를 만들어라.

In [90]:
np.ones_like(a)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

#### 문제 18
문제 15에서 만든 a와 shape과 dtype이 같고, 모든 원소가 7인 ndarray를 만들어라.

In [91]:
np.full_like(a,7)

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])