<h1 align='center'> 파이썬과학프로그래밍기초 기말고사</h1>

<h3 align='center'> 담당교수 : 박섭형</h3>

<p style="text-align: right"> 2021.6.16 (수)</p>

<div class="alert alert-block alert-info">
    
- 파일 이름에서 00000000을 자신의 학번으로, name을 자신의 이름으로 수정하세요.

- 다음 줄에 자신의 이름, 학번, 학과(전공)을 적으세요.

* 이름:   이장범          학번:20171722       학과(전공):러시아학과
    
</div>

- 주의 사항
  - 시험 시간: 오후 1:00 ~ 오후 2:20
  - 시험 시간 동안에는 카메라를 켜고 있어야 함
  - 오후 2:20에 줌을 종료하고 개인 동영상 녹화 시작
     - 녹화할 때 Jupyter notebook 화면이 전체 화면에 나오고 설명하는 자신의 얼굴이 화면 모퉁이에 함께 녹화되어야 함
     - 문제 하나당 설명 시간이 3분을 넘지 않도록 주의
  - SmartLead에 파일 upolad 마감 시간: 오후 3:00
  - Upload할 파일
     - ipynb 파일
     - 문제해설 녹화 동영상


#### 채점 결과 

- 학생들은 이곳에 아무 것도 기록하지 말기 바랍니다.

| 문제 | 문제 1 | 문제 2 | 문제 3 | 문제 42 | 문제 5 | 문제 6 | 문제 7 | 문제 8 | 합계 |
--|--|--|--|--|--|--|--|--|--
만점 | 10 | 10 | 10 | 10 | 10 | 10 | 20 | 20 | 100
득점 | | | | | | | |


### 문제 1.

변수 arr과 a는 다음과 같다.

```
arr: array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
a:   array([ 1,  0,  5,  7,  0, 11, 13,  0, 17, 19])
```
변수 arr과 a를 만드는 문장을 작성하라. 단, 원소를 직접 적으면 안된다.


In [97]:
import numpy as np
arr=np.arange(1,21,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [98]:
a=arr.where(arr==3, 0,arr)

AttributeError: 'numpy.ndarray' object has no attribute 'where'


### 문제 2.

아래 cell에서 변수 arr에 있는 정수 $n$ 중에서 $3 \le n \le 7$의 조건을 만족하는 숫자들을 원소로 갖는 ndarray a를 만들어라.

```
arr: array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7, 9,  2,  9])
a: array([5, 7, 5, 4, 5, 7])
```



In [18]:
np.random.seed(10)
arr = np.random.randint(1, 11, 20)
arr

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9])

In [99]:
b=np.where(a>=3
           a<=7,arr)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 문제 3.

다음 numpy ndarra arr를 만들어라.

```
arr: 
array([[ 1,  3,  5,  7],
       [ 3,  9, 15, 21],
       [ 5, 15, 25, 35],
       [ 7, 21, 35, 49]])
```



In [123]:
arr=np.arange(1,8,2)
arr2=np.arange(3,22,6)
arr3=np.arange(5,36,10)
arr4=np.arange(7,50,14)
k=np.hstack([arr,arr2,arr3,arr4]).reshape(1,4,4)
k

array([[[ 1,  3,  5,  7],
        [ 3,  9, 15, 21],
        [ 5, 15, 25, 35],
        [ 7, 21, 35, 49]]])

### 문제 4.

다음 numpy ndarra arr은 다음과 같다..

```
arr:
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```
이 arr로부터 다음 a를 만들어라.
```
a:
array([[ 1,  4,  3,  2],
       [ 5,  8,  7,  6],
       [ 9, 12, 11, 10],
       [13, 16, 15, 14]])
```

In [129]:
arr=np.arange(1,17).reshape(1,4,4)
print("arr:\n",arr)
a=np.hstack(arr[::-2,])
a

arr:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 문제 5.

아래 두 줄을 실행하면,  Pandas DataFrame 객체인 iris.data와 Pandas Series인 iris.target을 얻을 수 있다.

```
from sklearn import datasets
iris = datasets.load_iris(as_frame=True)
```
이 두 객체를 합친 새로운 Pandas DataFrame 객체인 new_iris를 만들어라.
```
new_iris:
	sepal length (cm)	sepal width (cm)	petal length (cm)	petal width (cm)	target
0	5.1	3.5	1.4	0.2	0
1	4.9	3.0	1.4	0.2	0
2	4.7	3.2	1.3	0.2	0
3	4.6	3.1	1.5	0.2	0
4	5.0	3.6	1.4	0.2	0
...	...	...	...	...	...
145	6.7	3.0	5.2	2.3	2
146	6.3	2.5	5.0	1.9	2
147	6.5	3.0	5.2	2.0	2
148	6.2	3.4	5.4	2.3	2
149	5.9	3.0	5.1	1.8	2
150 rows × 5 columns
```

In [68]:
from sklearn import datasets
iris = datasets.load_iris(as_frame=True)

In [87]:
print(pd.concat([iris.data, iris.target],axis=1))
    

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  

In [66]:
type(iris.target)

pandas.core.series.Series

### 문제 6.

문제 5에서 target이 0인 iris들의 꽃잎 길이(sepal length)의 평균과 표준편차를 구하라.

In [109]:
df1=pd.concat([iris.data, iris.target],axis=1)
print(df1['sepal length (cm)'].mean(axis=0))
print(df1['sepal length (cm)'].var(axis=0))

5.843333333333335
0.6856935123042505


### 문제 7.

다음은 현재 디렉토리에 있는 영상 파일 "nature-3082832_640.jpg"을 읽어서 numpy ndarray로 만드는 문장들이다.
```
import imageio
file_name = "nature-3082832_640.jpg"
img = imageio.imread(file_name)
```

img로부터 아래 영상을 만들어서 화면에 표시하라.

<img src='nature-3082832_640_cut.jpg' />

In [19]:
import imageio
file_name = "nature-3082832_640.jpg"
img = imageio.imread(file_name)

In [131]:
cols=121
rows=121
center=np.array([60,60])
radius=60
black=(0,0,0)
rect=np.full((rows,cols,3),black,np.uint8)
idx_r, idx_c=np.meshgrid(range(rows),range(cols))
idx=np.stack((idx_c,idx_r),-1)
rect[np.sum((idx-center)**2,-1)<=radius**2]=img
plt.imshow(rect)
plt.show

ValueError: shape mismatch: value array of shape (222,363,3) could not be broadcast to indexing result of shape (11289,3)


### 문제 8.

'temperature_anomalies.csv' 파일은 1880년부터 2021년까지 매년 5월의 지구 평균 온도를 측정하고, 이 온도에서 1910년부터 2000년까지의 평균 온도와의 차이를 나타난 데이터이다. (출처: https://www.ncdc.noaa.gov/cag/global/time-series/globe/land_ocean/1/5/1880-2021)

이 파일을 읽고, 다음 그래프와 최대한 닯은 그래프를 그려라.

단, matplot.pyplot 라이브러리를 사용하고, 그림의 크기는 가로 10 인치, 세로 4 인치로 하고, 
Value가 음수인 해의 그래프는 파란색으로, Value가 0 이상인 해의 그래프는 빨간색으로 표시하라.
<img src='global_temp_anomalies.png' />


In [63]:
import matplotlib.pyplot as plt
import pandas as pd
cols=4
rows=10
t=pd.read_csv("temperature_anomalies.csv")
t.set_index('Year',inplace=True)
plt.plot(t,t.Year,[-0.6,1.0,0.2])

AttributeError: 'DataFrame' object has no attribute 'Year'

In [60]:
t

Year  Value
0    1880  -0.10
1    1881   0.02
2    1882  -0.14
3    1883  -0.16
4    1884  -0.22
..    ...    ...
137  2017   0.87
138  2018   0.81
139  2019   0.86
140  2020   0.94
141  2021   0.81

[142 rows x 2 columns]